### PR TITLE
Remove CSR and self signed certificate creation

### PR DESCRIPTION
**Pull request by mcanevet**

### CODE REVIEW

**Comment by ckaenzig** [comment]
This doesn't just remove the CSR creation, but completely removes the generation of a self-signed certificate, am I right?

**Comment by mcanevet** [comment]
@ckaenzig yes indeed!
The goal of this is to converge a little bit more to `puppetlabs/apache` so that we can finally get rid of this module.

**Comment by mcanevet** [comment]
@ckaenzig I used the following PQL query to find all the occurrences of `apache_c2c::vhost::ssl` without `cert` specified and I fixed it by using `camptocamp/openssl` to generate a certificate and pass it to `ssl_cert` and `ssl_key` parameters:
```
resources[certname, title, file, line, environment,parameters] {  
  type = "Apache_c2c::Vhost::Ssl"
  and parameters.cert = false
}
```
I think I can merge this now

**Comment by ckaenzig** [comment]
@mcanevet Ok, then it's fine with me. Go for merge.

**Pull request merged**
